//! Integration tests against real HSM hardware or a simulator.
//!
//! !!! STALE — DO NOT TRUST THE VECTORS HERE !!!
//!
//! These tests predate the `fix/pin-block-format-mapping` handler audit and
//! encode the *old fabricated* wire formats (e.g. `C2 [mode][32H key]`, `CW`
//! with a mode byte, `CA` with `00/01/03/04` format codes, `M6` half-MAC = 2
//! bytes), and several now reference commands that have been gated (`LQ`/`JU`/
//! `KU`/`KY`). They also map against a standing test-key pool that has since
//! been deleted. Correctness coverage is moving to the in-process differential
//! property harness — see `docs/property-testing-plan.md`. Until rewritten,
//! treat passing/failing results here as meaningless. The framing helpers
//! (`make_thales_frame`, `parse_thales_response`) are still reusable.
//!
//! All tests here are `#[ignore]` by default. Run them with:
//!
//!   cargo test --test integration -- --ignored
//!
//! Required environment:
//!
//!   HSM_HOST     — IP or hostname of the HSM (or EFTSim endpoint)
//!   HSM_PORT     — TCP port (Futurex plain: 9000, TLS: 9100; Thales plain: 1500)
//!   PROXY_HOST   — host where this proxy is listening (default: 127.0.0.1)
//!   PROXY_PORT   — port the proxy is listening on (default: 1500)
//!   AWS_REGION   — AWS region for APC calls (default: us-east-1)
//!
//! Optional (for TLS tests):
//!   TLS_CERT     — path to client certificate PEM
//!   TLS_KEY      — path to client private key PEM
//!   TLS_CA       — path to CA certificate PEM for server verification
//!
//! Key mappings must match what is configured in proxy.yaml for the test environment.
//!
//! These tests validate end-to-end behavior: raw wire frames in, APC round-trip,
//! correct response framing out. They cannot be replaced by unit tests because
//! they exercise protocol fidelity, TLS negotiation, APC latency, and key mapping.
//!
//! ## Test key inventory (all in us-east-1, account 030716882260)
//!
//! Known-material keys (imported via KEY_CRYPTOGRAM — CyberChef cross-validation possible):
//!   LTEST_P0SRC_0001  P0 ZPK src   0123456789ABCDEF0123456789ABCDEF  KCV D5D44F
//!   LTEST_P0DST_0001  P0 ZPK dst   FEDCBA9876543210FEDCBA9876543210  KCV A68CDC
//!   LTEST_V1PVK_0001  V1 IBM PVK   112233445566778811223344556677AA  KCV 85A8D3
//!   LTEST_V2PVK_001_LTEST_V2PVK_001  V2 Visa PVK  AABBCCDDEEFF00011122334455667788  KCV 664CDA
//!   LTEST_B0BDK_001_LTEST_B0BDK_001  B0 BDK       0123456789ABCDEFFEDCBA9876543210  KCV 08D7B4
//!
//! APC-generated keys (no known material — Level 1 error-00 tests only):
//!   LIVETEST_MAC_001  M1 TDES MAC     KCV 33C58D
//!   LIVETEST_DEK_001  D0 TDES DEK     KCV 591C1F
//!   LTEST_M1_MAC_001  M1 TDES MAC     KCV 33C58D (same key as LIVETEST_MAC_001)
//!   LTEST_M3_MAC_001  M3 TDES MAC     KCV CA4575
//!   LTEST_M6_MAC_001  M6 AES-128 CMAC KCV 106AB5
//!   LTEST_HMAC_00001  M7 AES-128 HMAC KCV 9E55C6
//!   LTEST_CVK_000001  C0 TDES CVK     KCV 2AEB63
//!   LTEST_E0IMK_0001  E0 AES-256 ARQC KCV 9AA39D
//!
//! ## Test vectors derived from known material
//!
//! All vectors computed from the imported key material above:
//!
//! CA PIN translate (ISO Format 0, account 561237487695, PIN 1234):
//!   Cleartext PIN block  041262EDC8B7896A
//!   Encrypted under P0SRC  48B350B131BFCA28
//!
//! DA IBM 3624 verify (account 111111111111, PIN 1234, decim 0123456789012345):
//!   APC pad character = F → input to PVK: 111111111111FFFF
//!   Natural PIN (TDES(V1PVK, 111111111111FFFF) → decim): 2007
//!   Offset (customer 1234 − natural 2007 mod 10): 9237FFFFFFFF
//!   Encrypted PIN block under P0SRC: C30C31411AA3D043
//!
//! DC Visa PVV verify (account 111111111111, PIN 1234, PVKI 1):
//!   TSP = 11 rightmost PAN digits (excl check) || PVKI || PIN[0] || pad = 1111111111111000
//!   PVV = TDES(V2PVK, TSP_as_bytes) → first 4 decimal digits: 3361
//!   (Confirmed via APC generate_pin_data; V2PVK AABBCCDDEEFF00011122334455667788 KCV 664CDA)
//!   Encrypted PIN block under P0SRC (same block): C30C31411AA3D043
//!
//! CW/CY CVV (PAN 4111111111111111, expiry 0128, svc_code 101):
//!   CVV generated by APC with C0 CVK = 323 (round-trip — CY verifies CW output)

use std::io::{Read, Write};
use std::net::TcpStream;
use std::time::Duration;

fn proxy_addr() -> String {
    let host = std::env::var("PROXY_HOST").unwrap_or_else(|_| "127.0.0.1".to_string());
    let port = std::env::var("PROXY_PORT").unwrap_or_else(|_| "1500".to_string());
    format!("{host}:{port}")
}

fn send_recv(frame: &[u8]) -> Vec<u8> {
    let mut conn = TcpStream::connect(proxy_addr()).expect("connect to proxy");
    conn.set_read_timeout(Some(Duration::from_secs(10)))
        .expect("set_read_timeout on TcpStream should not fail");
    conn.write_all(frame).expect("send frame");
    let mut resp = vec![0u8; 4096];
    let n = conn.read(&mut resp).expect("read response");
    resp[..n].to_vec()
}

// ── Thales payShield wire helpers ─────────────────────────────────────────────

fn make_thales_frame(header: [u8; 2], cmd: &[u8], payload: &[u8]) -> Vec<u8> {
    let body_len = 2 + cmd.len() + payload.len();
    let mut out = Vec::new();
    out.extend_from_slice(&(body_len as u16).to_be_bytes());
    out.extend_from_slice(&header);
    out.extend_from_slice(cmd);
    out.extend_from_slice(payload);
    out
}

fn parse_thales_response(resp: &[u8]) -> (Vec<u8>, Vec<u8>) {
    // [2B length][2B header][2B response_code][2B error_code][payload]
    assert!(resp.len() >= 8, "response too short: {} bytes", resp.len());
    let error_code = resp[6..8].to_vec();
    let payload = resp[8..].to_vec();
    (error_code, payload)
}

fn assert_ec00(resp: &[u8], context: &str) {
    let (ec, _) = parse_thales_response(resp);
    assert_eq!(
        &ec,
        b"00",
        "{context}: expected error code 00, got: {}",
        String::from_utf8_lossy(&ec)
    );
}

fn assert_not_ec68(resp: &[u8], context: &str) {
    let (ec, _) = parse_thales_response(resp);
    assert_ne!(
        &ec, b"68",
        "{context}: got error 68 (unrecognised command) — handler not registered"
    );
}

// ── B2 Heartbeat ─────────────────────────────────────────────────────────────

/// B2 diagnostics (heartbeat): no APC call, proxy responds locally.
#[test]
#[ignore = "requires live proxy (set PROXY_HOST, PROXY_PORT)"]
fn thales_b2_heartbeat_returns_success() {
    let frame = make_thales_frame([0x00, 0x00], b"B2", b"");
    let resp = send_recv(&frame);
    let (error_code, _payload) = parse_thales_response(&resp);
    assert_eq!(&error_code, b"00", "expected error code 00 (success)");
}

// ── MA/MC ISO 9797 Alg 1 MAC ─────────────────────────────────────────────────

/// MA/MC round-trip: generate a MAC under a real APC key then verify it.
/// Proves the proxy translates both directions and that the 8H truncation is correct.
#[test]
#[ignore = "requires live proxy with LIVETEST_MAC_001 in proxy.yaml (see AGENTS.md live test procedure)"]
fn thales_ma_mc_roundtrip_live() {
    // MA: generate MAC — key(16) + message
    let mut ma_payload = b"LIVETEST_MAC_001".to_vec();
    ma_payload.extend_from_slice(b"LIVE TEST MESSAGE");
    let ma_frame = make_thales_frame([0x00, 0x00], b"MA", &ma_payload);
    let ma_resp = send_recv(&ma_frame);
    let (ec, mac) = parse_thales_response(&ma_resp);
    assert_eq!(
        &ec,
        b"00",
        "MA should succeed; got: {}",
        String::from_utf8_lossy(&ma_resp)
    );
    assert_eq!(
        mac.len(),
        8,
        "MA should return 8 hex chars (4 bytes); got {} chars",
        mac.len()
    );

    // MC: verify the MAC we just generated — key(16) + mac(8H) + message
    let mut mc_payload = b"LIVETEST_MAC_001".to_vec();
    mc_payload.extend_from_slice(&mac);
    mc_payload.extend_from_slice(b"LIVE TEST MESSAGE");
    let mc_frame = make_thales_frame([0x00, 0x00], b"MC", &mc_payload);
    let mc_resp = send_recv(&mc_frame);
    let (ec, _) = parse_thales_response(&mc_resp);
    assert_eq!(
        &ec,
        b"00",
        "MC round-trip verify should succeed; got: {}",
        String::from_utf8_lossy(&mc_resp)
    );
}

// ── HE/HG Data Encrypt/Decrypt ───────────────────────────────────────────────

/// HE/HG round-trip: encrypt a block then decrypt it back.
/// Proves the DEK key path and that the plaintext survives the round-trip.
#[test]
#[ignore = "requires live proxy with LIVETEST_DEK_001 in proxy.yaml (see AGENTS.md live test procedure)"]
fn thales_he_hg_roundtrip_live() {
    let plaintext_hex = b"AABBCCDDEE112233"; // 8 bytes as 16H

    // HE: encrypt — key(16) + plaintext_hex(16H)
    let mut he_payload = b"LIVETEST_DEK_001".to_vec();
    he_payload.extend_from_slice(plaintext_hex);
    let he_frame = make_thales_frame([0x00, 0x00], b"HE", &he_payload);
    let he_resp = send_recv(&he_frame);
    let (ec, ciphertext) = parse_thales_response(&he_resp);
    assert_eq!(
        &ec,
        b"00",
        "HE should succeed; got: {}",
        String::from_utf8_lossy(&he_resp)
    );
    assert!(!ciphertext.is_empty(), "HE should return ciphertext");

    // HG: decrypt — key(16) + ciphertext(16H)
    let mut hg_payload = b"LIVETEST_DEK_001".to_vec();
    hg_payload.extend_from_slice(&ciphertext);
    let hg_frame = make_thales_frame([0x00, 0x00], b"HG", &hg_payload);
    let hg_resp = send_recv(&hg_frame);
    let (ec, recovered) = parse_thales_response(&hg_resp);
    assert_eq!(
        &ec,
        b"00",
        "HG should succeed; got: {}",
        String::from_utf8_lossy(&hg_resp)
    );
    assert_eq!(
        recovered,
        plaintext_hex,
        "HG should recover original plaintext; got: {}",
        String::from_utf8_lossy(&recovered)
    );
}

// ── HE with TR-31 wrapped key block ('S' prefix) ────────────────────────────

/// Build an X9.143 / TR-31 ASCII key block (without 'S' prefix) carrying a KC
/// optional block. The encrypted-key-data + MAC region is filler — the proxy
/// only reads the header + optional blocks for KCV-based resolution, then
/// hands off to APC by ARN. APC operates on the already-imported clear key.
fn build_tr31_with_kc(usage: [u8; 2], algo: u8, kcv: &str) -> Vec<u8> {
    let kc = format!("KC0C00{kcv}"); // ID=KC, len=0C(12), version=00, 6-char KCV
    assert_eq!(kc.len(), 12);
    let header_no_len = format!(
        "D____{u0}{u1}{a}B00N0100",
        u0 = usage[0] as char,
        u1 = usage[1] as char,
        a = algo as char,
    );
    let total_len: usize = 80;
    let mut header = header_no_len.into_bytes();
    let len_str = format!("{total_len:04}");
    header[1..5].copy_from_slice(len_str.as_bytes());
    assert_eq!(header.len(), 16);

    let padding_len = total_len - header.len() - kc.len();
    let padding: Vec<u8> = std::iter::repeat_n(b'0', padding_len).collect();

    let mut block = Vec::with_capacity(total_len);
    block.extend_from_slice(&header);
    block.extend_from_slice(kc.as_bytes());
    block.extend_from_slice(&padding);
    assert_eq!(block.len(), total_len);
    block
}

/// End-to-end wrapped-key test: the proxy must extract the KCV from the TR-31
/// "KC" optional block and resolve it against the APC inventory loaded at
/// startup — no `key_mappings` entry exists for this wire form, so success
/// proves the KCV path. The known-material D0 DEK (KCV=57860B) must exist in
/// APC and be the only key with that (usage, algorithm, kcv).
#[test]
#[ignore = "requires live proxy with the D0 DEK KCV=57860B in APC inventory"]
fn thales_he_resolves_wrapped_key_via_kcv() {
    let plaintext_hex = b"AABBCCDDEE112233"; // 8 bytes as 16H

    // Build the wrapped key field: 'S' + 80-char TR-31 block declaring D0/TDES
    // with KC optional block carrying the D0 DEK's KCV (57860B).
    let tr31 = build_tr31_with_kc(*b"D0", b'T', "57860B");
    let mut he_payload = vec![b'S'];
    he_payload.extend_from_slice(&tr31);
    he_payload.extend_from_slice(plaintext_hex);

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"HE", &he_payload));
    let (ec, ciphertext) = parse_thales_response(&resp);
    assert_eq!(
        &ec,
        b"00",
        "wrapped HE should succeed via KCV resolution; got: {}",
        String::from_utf8_lossy(&resp)
    );
    assert_eq!(
        ciphertext.len(),
        16,
        "HE should return 16H ciphertext; got {} chars",
        ciphertext.len()
    );

    // Round-trip via HG using the same wrapped block: confirms the same ARN
    // is selected (resolver is deterministic) and the encrypt/decrypt pair
    // recovers the original plaintext.
    let mut hg_payload = vec![b'S'];
    hg_payload.extend_from_slice(&tr31);
    hg_payload.extend_from_slice(&ciphertext);
    let resp2 = send_recv(&make_thales_frame([0x00, 0x00], b"HG", &hg_payload));
    let (ec2, recovered) = parse_thales_response(&resp2);
    assert_eq!(
        &ec2,
        b"00",
        "wrapped HG should succeed: {}",
        String::from_utf8_lossy(&resp2)
    );
    assert_eq!(
        recovered, plaintext_hex,
        "HG via wrapped key should recover plaintext"
    );
}

/// Wrapped-key resolution failure case: KCV in the block doesn't match any
/// APC key, proxy should refuse with error 10 (KeyNotFound), not silently
/// fall through to label config or a wrong key.
#[test]
#[ignore = "requires live proxy"]
fn thales_he_wrapped_key_unknown_kcv_returns_10() {
    let tr31 = build_tr31_with_kc(*b"D0", b'T', "DEADBE"); // not a real KCV
    let mut payload = vec![b'S'];
    payload.extend_from_slice(&tr31);
    payload.extend_from_slice(b"AABBCCDDEE112233");

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"HE", &payload));
    let (ec, _) = parse_thales_response(&resp);
    assert_eq!(
        &ec,
        b"10",
        "unknown wrapped-key KCV should map to error 10 (KeyNotFound); got: {}",
        String::from_utf8_lossy(&ec)
    );
}

// ── C2/C4 MAC (32H key, fixed layout) ────────────────────────────────────────

/// C2/C4 Alg1 round-trip: generate then verify an ISO 9797 Alg 1 MAC.
/// C2/C4 key field is always 32H (no parse_legacy_key prefix detection).
#[test]
#[ignore = "requires live proxy with LTEST_M1_MAC_001LTEST_M1_MAC_001 in proxy.yaml"]
fn thales_c2_c4_alg1_roundtrip() {
    // C2 payload: [mode(1)][key(32H)][msg_len(4H)][message]
    // mode '0' = Alg1
    let mut c2_payload = vec![b'0'];
    c2_payload.extend_from_slice(b"LTEST_M1_MAC_001LTEST_M1_MAC_001"); // 32H key
    c2_payload.extend_from_slice(b"0004"); // 4 bytes
    c2_payload.extend_from_slice(b"DEADBEEF");
    let c2_resp = send_recv(&make_thales_frame([0x00, 0x00], b"C2", &c2_payload));
    let (ec, mac) = parse_thales_response(&c2_resp);
    assert_eq!(
        &ec,
        b"00",
        "C2 Alg1 generate failed: {}",
        String::from_utf8_lossy(&ec)
    );
    assert_eq!(mac.len(), 8, "C2 should return 8H (4-byte) MAC");

    // C4 verify: [mode][key(32H)][msg_len(4H)][message][mac(8H)]
    let mut c4_payload = vec![b'0'];
    c4_payload.extend_from_slice(b"LTEST_M1_MAC_001LTEST_M1_MAC_001");
    c4_payload.extend_from_slice(b"0004");
    c4_payload.extend_from_slice(b"DEADBEEF");
    c4_payload.extend_from_slice(&mac);
    let c4_resp = send_recv(&make_thales_frame([0x00, 0x00], b"C4", &c4_payload));
    assert_ec00(&c4_resp, "C4 Alg1 verify");
}

/// C2/C4 Alg3 round-trip: generate then verify an ISO 9797 Alg 3 (Retail MAC).
#[test]
#[ignore = "requires live proxy with LTEST_M3_MAC_001LTEST_M3_MAC_001 in proxy.yaml"]
fn thales_c2_c4_alg3_roundtrip() {
    // mode '1' = Alg3
    let mut c2_payload = vec![b'1'];
    c2_payload.extend_from_slice(b"LTEST_M3_MAC_001LTEST_M3_MAC_001"); // 32H key
    c2_payload.extend_from_slice(b"0008"); // 8 bytes
    c2_payload.extend_from_slice(b"CAFEBABE01020304");
    let c2_resp = send_recv(&make_thales_frame([0x00, 0x00], b"C2", &c2_payload));
    let (ec, mac) = parse_thales_response(&c2_resp);
    assert_eq!(
        &ec,
        b"00",
        "C2 Alg3 generate failed: {}",
        String::from_utf8_lossy(&ec)
    );
    assert_eq!(mac.len(), 8, "C2 Alg3 should return 8H MAC");

    let mut c4_payload = vec![b'1'];
    c4_payload.extend_from_slice(b"LTEST_M3_MAC_001LTEST_M3_MAC_001");
    c4_payload.extend_from_slice(b"0008");
    c4_payload.extend_from_slice(b"CAFEBABE01020304");
    c4_payload.extend_from_slice(&mac);
    let c4_resp = send_recv(&make_thales_frame([0x00, 0x00], b"C4", &c4_payload));
    assert_ec00(&c4_resp, "C4 Alg3 verify");
}

// ── M6/M8 Extended MAC (parse_legacy_key, variable layout) ───────────────────

/// Build an M6/M8 payload with a 16H single-length key.
fn m6_payload_16h(algo: u8, mac_size: u8, key_label: &[u8], msg_hex: &[u8]) -> Vec<u8> {
    let mut p = vec![b'0', b'1', mac_size, algo, b'1']; // mode+infmt+macsize+algo+pad
    p.extend_from_slice(b"MA1"); // key type 3H (consumed)
    p.extend_from_slice(key_label); // 16H key
    let byte_count = msg_hex.len() / 2;
    p.extend_from_slice(format!("{byte_count:04X}").as_bytes());
    p.extend_from_slice(msg_hex);
    p
}

/// M6/M8 Alg1 round-trip with M1 key.
#[test]
#[ignore = "requires live proxy with LTEST_M1_MAC_001 in proxy.yaml"]
fn thales_m6_m8_alg1_roundtrip() {
    let p = m6_payload_16h(b'1', b'0', b"LTEST_M1_MAC_001", b"AABBCCDD");
    let m6_resp = send_recv(&make_thales_frame([0x00, 0x00], b"M6", &p));
    let (ec, mac) = parse_thales_response(&m6_resp);
    assert_eq!(
        &ec,
        b"00",
        "M6 Alg1 failed: {}",
        String::from_utf8_lossy(&ec)
    );
    assert_eq!(
        mac.len(),
        8,
        "M6 Alg1 should return 8H MAC (mac_size=0 → 4 bytes)"
    );

    let mut verify_p = m6_payload_16h(b'1', b'0', b"LTEST_M1_MAC_001", b"AABBCCDD");
    verify_p.extend_from_slice(&mac);
    let m8_resp = send_recv(&make_thales_frame([0x00, 0x00], b"M8", &verify_p));
    assert_ec00(&m8_resp, "M8 Alg1 verify");
}

/// M6/M8 Alg3 round-trip with M3 key.
#[test]
#[ignore = "requires live proxy with LTEST_M3_MAC_001 in proxy.yaml"]
fn thales_m6_m8_alg3_roundtrip() {
    let p = m6_payload_16h(b'3', b'0', b"LTEST_M3_MAC_001", b"01020304");
    let m6_resp = send_recv(&make_thales_frame([0x00, 0x00], b"M6", &p));
    let (ec, mac) = parse_thales_response(&m6_resp);
    assert_eq!(
        &ec,
        b"00",
        "M6 Alg3 failed: {}",
        String::from_utf8_lossy(&ec)
    );

    let mut verify_p = m6_payload_16h(b'3', b'0', b"LTEST_M3_MAC_001", b"01020304");
    verify_p.extend_from_slice(&mac);
    let m8_resp = send_recv(&make_thales_frame([0x00, 0x00], b"M8", &verify_p));
    assert_ec00(&m8_resp, "M8 Alg3 verify");
}

/// M6/M8 CMAC round-trip with AES-128 M6 key.
/// CMAC in APC is AES-based — this exercises the AES CMAC path.
/// APC CMAC requires message_data ≥ 16 hex chars (8 bytes); shorter messages
/// are rejected with ValidationException. APC returns a full 32H (16-byte) AES-CMAC;
/// the handler truncates to 8H (4 bytes) for mac_size=0.
#[test]
#[ignore = "requires live proxy with LTEST_M6_MAC_001 in proxy.yaml"]
fn thales_m6_m8_cmac_roundtrip() {
    // APC CMAC minimum message length is 8 bytes (16H); use 16H message
    let p = m6_payload_16h(b'6', b'0', b"LTEST_M6_MAC_001", b"FEEDFACEDEADBEEF");
    let m6_resp = send_recv(&make_thales_frame([0x00, 0x00], b"M6", &p));
    let (ec, mac) = parse_thales_response(&m6_resp);
    assert_eq!(
        &ec,
        b"00",
        "M6 CMAC failed: {}",
        String::from_utf8_lossy(&ec)
    );
    assert_eq!(
        mac.len(),
        8,
        "M6 CMAC mac_size=0 → 4 bytes → 8H output (truncated from 32H AES-CMAC)"
    );

    let mut verify_p = m6_payload_16h(b'6', b'0', b"LTEST_M6_MAC_001", b"FEEDFACEDEADBEEF");
    verify_p.extend_from_slice(&mac);
    let m8_resp = send_recv(&make_thales_frame([0x00, 0x00], b"M8", &verify_p));
    assert_ec00(&m8_resp, "M8 CMAC verify");
}

/// M6 half-MAC (mac_size '1' = 2 bytes → 4H output).
#[test]
#[ignore = "requires live proxy with LTEST_M1_MAC_001 in proxy.yaml"]
fn thales_m6_half_mac_size() {
    let p = m6_payload_16h(b'1', b'1', b"LTEST_M1_MAC_001", b"AABBCCDD");
    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"M6", &p));
    let (ec, mac) = parse_thales_response(&resp);
    assert_eq!(&ec, b"00", "M6 half-MAC failed");
    assert_eq!(mac.len(), 4, "mac_size=1 → 2 bytes → 4H output");
}

// ── LQ/LS HMAC ───────────────────────────────────────────────────────────────

/// LQ/LS HMAC-SHA256 round-trip.
/// LQ payload: [sha_variant(1)][key(16H)][msg_len(4H)][message_hex]
/// LS appends the HMAC to verify.
#[test]
#[ignore = "requires live proxy with LTEST_HMAC_00001 in proxy.yaml"]
fn thales_lq_ls_hmac_sha256_roundtrip() {
    // sha_variant '2' = SHA-256; key = 16H; msg = 4 bytes hex-encoded
    let mut lq_payload = vec![b'2'];
    lq_payload.extend_from_slice(b"LTEST_HMAC_00001");
    lq_payload.extend_from_slice(b"0004"); // 4 bytes
    lq_payload.extend_from_slice(b"DEADBEEF");

    let lq_resp = send_recv(&make_thales_frame([0x00, 0x00], b"LQ", &lq_payload));
    let (ec, hmac) = parse_thales_response(&lq_resp);
    assert_eq!(
        &ec,
        b"00",
        "LQ HMAC-SHA256 failed: {}",
        String::from_utf8_lossy(&ec)
    );
    // HMAC-SHA256 = 32 bytes = 64 hex chars
    assert_eq!(
        hmac.len(),
        64,
        "LQ should return 64H HMAC-SHA256; got {} chars",
        hmac.len()
    );

    // LS: verify — same as LQ payload with HMAC appended
    let mut ls_payload = vec![b'2'];
    ls_payload.extend_from_slice(b"LTEST_HMAC_00001");
    ls_payload.extend_from_slice(b"0004");
    ls_payload.extend_from_slice(b"DEADBEEF");
    ls_payload.extend_from_slice(&hmac);

    let ls_resp = send_recv(&make_thales_frame([0x00, 0x00], b"LS", &ls_payload));
    assert_ec00(&ls_resp, "LS HMAC-SHA256 verify");
}

// ── CW/CY CVV Generate/Verify ─────────────────────────────────────────────────

/// CW/CY CVV round-trip: generate CVV then verify it.
/// Level 1 — CW captures the CVV, CY verifies the same value.
/// The C0 CVK has no known material so we cannot pre-compute expected CVV.
///
/// CW payload: mode(1) + cvk(32H) + pan(16N) + expiry(4) + svc_code(3)
/// CVK is a fixed 32H field (bytes 1..33, no parse_legacy_key prefix detection).
#[test]
#[ignore = "requires live proxy with LTEST_CVK_000001LTEST_CVK_000001 in proxy.yaml"]
fn thales_cw_cy_cvv_roundtrip() {
    // CW payload: mode(1) + cvk(32H) + pan(16N) + expiry(MMYY 4) + svc_code(3)
    let mut cw_p = vec![b'0']; // mode = CVV1
    cw_p.extend_from_slice(b"LTEST_CVK_000001LTEST_CVK_000001"); // 32H key label
    cw_p.extend_from_slice(b"4111111111111111"); // PAN 16N
    cw_p.extend_from_slice(b"0128"); // expiry MMYY
    cw_p.extend_from_slice(b"101"); // service code
    let cw_resp = send_recv(&make_thales_frame([0x00, 0x00], b"CW", &cw_p));
    let (ec, cvv) = parse_thales_response(&cw_resp);
    assert_eq!(
        &ec,
        b"00",
        "CW CVV generate failed: {}",
        String::from_utf8_lossy(&ec)
    );
    assert_eq!(
        cvv.len(),
        3,
        "CW should return 3-digit CVV; got {} chars",
        cvv.len()
    );

    // CY: verify — same data + captured CVV
    // CY payload: mode(1) + cvk(32H) + cvv(3N) + pan(16N) + expiry(4) + svc_code(3)
    let mut cy_p = vec![b'0'];
    cy_p.extend_from_slice(b"LTEST_CVK_000001LTEST_CVK_000001"); // 32H key label
    cy_p.extend_from_slice(&cvv); // 3-digit CVV to verify
    cy_p.extend_from_slice(b"4111111111111111");
    cy_p.extend_from_slice(b"0128");
    cy_p.extend_from_slice(b"101");
    let cy_resp = send_recv(&make_thales_frame([0x00, 0x00], b"CY", &cy_p));
    assert_ec00(&cy_resp, "CY CVV verify");
}

// ── CA PIN Translate ──────────────────────────────────────────────────────────

/// CA PIN translate: ISO Format 0 PIN block under known ZPK src → ZPK dst.
///
/// Level 2 (known material): the encrypted PIN block is pre-computed from
/// ZPK src material 0123456789ABCDEF0123456789ABCDEF for PIN=1234,
/// account=561237487695. APC decrypts and re-encrypts under ZPK dst.
///
/// CA payload layout:
///   [0]      src key type  1N  '0'=TDES
///   [1]      dst key type  1N  '0'=TDES
///   [2..34]  src key       32H  (mapped via key_mappings)
///   [34..66] dst key       32H  (mapped via key_mappings)
///   [66..68] max PIN len   2N
///   [68..70] src format    2N  "00"=ISO Format 0
///   [70..72] dst format    2N  "00"=ISO Format 0
///   [72..88] PIN block     16H  (encrypted under src ZPK)
///   [88..100] account      12N  (rightmost 12 PAN digits excl check)
#[test]
#[ignore = "requires live proxy with known-material P0 keys in proxy.yaml"]
fn thales_ca_pin_translate_known_material() {
    let mut payload = Vec::new();
    payload.push(b'0'); // src key type = TDES
    payload.push(b'0'); // dst key type = TDES
    payload.extend_from_slice(b"LTEST_P0SRC_0001_LTEST_P0SRC_001"); // src 32H
    payload.extend_from_slice(b"LTEST_P0DST_0001_LTEST_P0DST_001"); // dst 32H
    payload.extend_from_slice(b"12"); // max PIN len
    payload.extend_from_slice(b"00"); // src format = ISO Format 0
    payload.extend_from_slice(b"00"); // dst format = ISO Format 0
    payload.extend_from_slice(b"48B350B131BFCA28"); // encrypted PIN block (PIN=1234, acct=561237487695)
    payload.extend_from_slice(b"561237487695"); // account

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"CA", &payload));
    let (ec, translated) = parse_thales_response(&resp);
    assert_eq!(
        &ec,
        b"00",
        "CA PIN translate failed: {}",
        String::from_utf8_lossy(&ec)
    );
    assert_eq!(
        translated.len(),
        17,
        "CA response: 16H translated PIN block + 1 byte flag"
    );
}

// ── DA IBM 3624 PIN Verify ────────────────────────────────────────────────────

/// DA IBM 3624 PIN verify: correct PIN+offset should return 00.
///
/// Level 2 (known material): all values derived from known V1 PVK and P0 ZPK
/// material. See file-header comment for the derivation.
///
/// DA payload layout (parse_legacy_key for both keys):
///   enc_key (16H) + pvk (16H) + max_pin(2N) + min_pin(2N)
///   + pin_block(16H) + pin_fmt(2N) + account(12N)
///   + decim_table(16H) + pin_val_data(12A) + offset(12H)
#[test]
#[ignore = "requires live proxy with known-material V1 and P0SRC keys in proxy.yaml"]
fn thales_da_ibm3624_verify_correct_pin() {
    let mut payload = Vec::new();
    payload.extend_from_slice(b"LTEST_P0SRC_0001"); // enc key 16H
    payload.extend_from_slice(b"LTEST_V1PVK_0001"); // V1 PVK 16H
    payload.extend_from_slice(b"12"); // max PIN len
    payload.extend_from_slice(b"04"); // min PIN len
    payload.extend_from_slice(b"C30C31411AA3D043"); // encrypted PIN block (PIN=1234, acct=111111111111)
    payload.extend_from_slice(b"00"); // PIN block format (consumed; proxy hardcodes IsoFormat0)
    payload.extend_from_slice(b"111111111111"); // account 12N
    payload.extend_from_slice(b"0123456789012345"); // decimalization table 16H (identity)
    payload.extend_from_slice(b"111111111111"); // PIN validation data 12A
    payload.extend_from_slice(b"9237FFFFFFFF"); // IBM offset 12H (PIN 1234, natural 2007)

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"DA", &payload));
    assert_ec00(&resp, "DA IBM 3624 PIN verify (correct PIN)");
}

// ── DC Visa PVV PIN Verify ────────────────────────────────────────────────────

/// DC Visa PVV PIN verify: correct PIN+PVV should return 00.
///
/// Level 2 (known material): PVV derived from V2 PVK material
/// AABBCCDDEEFF00011122334455667788, PAN 111111111111, PVKI 1, PIN 1234.
/// Computed PVV = 4206.
///
/// DC payload layout:
///   enc_key (parse_legacy_key 16H) + pvk_pair (parse_key_32 32H)
///   + max_pin(2N) + min_pin(2N) + pin_block(16H) + pin_fmt(2N)
///   + account(12N) + pvki(1N) + pvv(4N)
#[test]
#[ignore = "requires live proxy with known-material V2 and P0SRC keys in proxy.yaml"]
fn thales_dc_visa_pvv_verify_correct_pin() {
    let mut payload = Vec::new();
    payload.extend_from_slice(b"LTEST_P0SRC_0001"); // enc key 16H (parse_legacy_key)
    payload.extend_from_slice(b"LTEST_V2PVK_0001LTEST_V2PVK_0001"); // V2 PVK 32H (parse_key_32)
    payload.extend_from_slice(b"12"); // max PIN len
    payload.extend_from_slice(b"04"); // min PIN len
    payload.extend_from_slice(b"C30C31411AA3D043"); // encrypted PIN block
    payload.extend_from_slice(b"00"); // PIN block format (consumed)
    payload.extend_from_slice(b"111111111111"); // account 12N
    payload.push(b'1'); // PVKI = 1
    payload.extend_from_slice(b"3361"); // Visa PVV (APC-confirmed for PIN=1234, PAN=111111111111, PVKI=1)

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"DC", &payload));
    assert_ec00(&resp, "DC Visa PVV verify (correct PIN)");
}

// ── GW DUKPT MAC ─────────────────────────────────────────────────────────────

/// GW DUKPT Alg3 MAC round-trip using known BDK material.
///
/// GW payload layout:
/// ```text
/// mode(1) + infmt(1) + macsize(1) + algo(1) + pad(1)
/// + BDK (parse_bdk 32H) + KSN_desc(3H) + KSN(20H for TDES)
/// + msg_len(4H) + message_hex
/// verify appends: mac(8H)
/// ```
///
/// KSN descriptor "014": key_type=0, nibble_count=0x14=20 → 20H TDES KSN.
#[test]
#[ignore = "requires live proxy with known-material B0 BDK key in proxy.yaml"]
fn thales_gw_dukpt_alg3_mac_roundtrip() {
    let build_gw = |is_verify: bool, mac: &[u8]| {
        let mut p = Vec::new();
        p.push(if is_verify { b'1' } else { b'0' }); // mode
        p.push(b'1'); // infmt = hex
        p.push(b'0'); // macsize = 4 bytes
        p.push(b'3'); // algo = Alg3
        p.push(b'1'); // pad method (consumed)
        p.extend_from_slice(b"LTEST_B0BDK_0001LTEST_B0BDK_0001"); // BDK 32H (parse_bdk)
        p.extend_from_slice(b"014"); // KSN descriptor: nibbles=0x14=20 → TDES
        p.extend_from_slice(b"FFFF9876543210E00001"); // 20H TDES KSN
        p.extend_from_slice(b"0008"); // 8 bytes message
        p.extend_from_slice(b"AABBCCDD11223344"); // message hex
        if is_verify {
            p.extend_from_slice(mac);
        }
        p
    };

    // Generate
    let gen_resp = send_recv(&make_thales_frame(
        [0x00, 0x00],
        b"GW",
        &build_gw(false, &[]),
    ));
    let (ec, mac) = parse_thales_response(&gen_resp);
    assert_eq!(
        &ec,
        b"00",
        "GW DUKPT Alg3 generate failed: {}",
        String::from_utf8_lossy(&ec)
    );
    assert_eq!(mac.len(), 8, "GW mac_size=0 → 4 bytes → 8H");

    // Verify
    let ver_resp = send_recv(&make_thales_frame(
        [0x00, 0x00],
        b"GW",
        &build_gw(true, &mac),
    ));
    assert_ec00(&ver_resp, "GW DUKPT Alg3 verify");
}

// ── KQ ARQC Verify ───────────────────────────────────────────────────────────

/// KQ ARQC verify: confirms the proxy reaches APC (error 00 or ARQC mismatch,
/// never 68 "unrecognised command").
///
/// The E0 key has no known material (APC-generated), so the dummy ARQC will fail
/// cryptographic verification. We only assert the command is handled (not error 68).
///
/// KQ payload layout (binary fields after ASCII header):
///   mode(1) + scheme(1) + key_type(3H) + key(parse_legacy_key 16H)
///   + pan_seq(8B BCD: 6B PAN + 1B seq + 1B 0xFF pad)
///   + ATC(2B BE) + UN(4B) + txn_len(2B BE) + txn_data(n bytes)
///   + 0x3B delimiter + ARQC(8B)
#[test]
#[ignore = "requires live proxy with LTEST_E0IMK_0001 in proxy.yaml"]
fn thales_kq_arqc_verify_reaches_apc() {
    let mut payload = Vec::new();
    payload.push(b'0'); // mode 0 = verify ARQC only
    payload.push(b'1'); // scheme 1 = Mastercard M/Chip (Option A + Mastercard SKD)
    payload.extend_from_slice(b"000"); // key type 3H (consumed)
    payload.extend_from_slice(b"LTEST_E0IMK_0001"); // E0 AES-256 key 16H
                                                    // PAN/PSN: EMV pre-formatted, rightmost 16 of (PAN 4111111111111111 || PSN 01) = 1111111111111101
    payload.extend_from_slice(&[0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x01]);
    payload.extend_from_slice(&[0x00, 0x01]); // ATC = 0x0001
    payload.extend_from_slice(&[0x01, 0x02, 0x03, 0x04]); // UN
    payload.extend_from_slice(&[0x00, 0x10]); // txn_data length = 16 bytes
                                              // Transaction data (PDOL): 16 bytes of test data
    payload.extend_from_slice(&[
        0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x08, 0x40, 0x16, 0x05, 0x30, 0x00, 0x00, 0x00, 0x00,
        0x00,
    ]);
    payload.push(0x3B); // delimiter
                        // Dummy ARQC (will fail verification — that's expected for Level 1)
    payload.extend_from_slice(&[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]);

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"KQ", &payload));
    assert_not_ec68(&resp, "KQ ARQC verify");
    // error 00 = valid ARQC (unlikely with dummy bytes)
    // any other non-68 code = handler reached APC (verification failed, as expected)
    let (ec, _) = parse_thales_response(&resp);
    println!("KQ response error code: {}", String::from_utf8_lossy(&ec));
}

// ── JU Issuer Script MAC ──────────────────────────────────────────────────────

/// JU issuer script MAC: generate an EMV issuer script integrity MAC.
///
/// JU/KU/KY payload (binary fields):
///   mode(1) + scheme(1) + key_type(3H) + key(parse_legacy_key 16H)
///   + pan_seq(8B BCD) + ATC(2B) + mac_data_len(4H) + mac_data(nB) + ';'
///
/// The handler calls generate_mac with ISO9797_ALGORITHM3 on the mapped key.
#[test]
#[ignore = "requires live proxy with LTEST_M3_MAC_001 in proxy.yaml"]
fn thales_ju_issuer_script_mac_generates() {
    let mut payload = Vec::new();
    payload.push(b'0'); // mode 0 = integrity only
    payload.push(b'0'); // scheme 0 = Visa/Amex EMV Option A
    payload.extend_from_slice(b"000"); // key type 3H (consumed)
    payload.extend_from_slice(b"LTEST_M3_MAC_001"); // M3 key 16H
                                                    // PAN+seq BCD: PAN 411111111111 + seq 01 + 0xFF pad = 8 bytes
    payload.extend_from_slice(&[0x41, 0x11, 0x11, 0x11, 0x11, 0x11, 0x01, 0xFF]);
    payload.extend_from_slice(&[0x00, 0x01]); // ATC
    payload.extend_from_slice(b"0004"); // MAC data length = 4 bytes (hex)
    payload.extend_from_slice(&[0xDE, 0xAD, 0xBE, 0xEF]); // MAC data (binary)
    payload.push(b';'); // delimiter

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"JU", &payload));
    let (ec, mac) = parse_thales_response(&resp);
    assert_eq!(
        &ec,
        b"00",
        "JU issuer script MAC failed: {}",
        String::from_utf8_lossy(&ec)
    );
    assert_eq!(
        mac.len(),
        8,
        "JU should return 8H MAC (4 bytes) — APC ISO9797_ALGORITHM3 returns 4-byte truncated MAC"
    );
}

// ── KU/KY Issuer Script MAC (EMV 3.1.1 / EMV 4.x) ───────────────────────────

/// KU: same wire format as JU, different command code (EMV 3.1.1).
#[test]
#[ignore = "requires live proxy with LTEST_M3_MAC_001 in proxy.yaml"]
fn thales_ku_issuer_script_mac_generates() {
    let mut payload = Vec::new();
    payload.push(b'0');
    payload.push(b'0');
    payload.extend_from_slice(b"000");
    payload.extend_from_slice(b"LTEST_M3_MAC_001");
    payload.extend_from_slice(&[0x41, 0x11, 0x11, 0x11, 0x11, 0x11, 0x01, 0xFF]);
    payload.extend_from_slice(&[0x00, 0x02]); // ATC = 2 (different from JU)
    payload.extend_from_slice(b"0004");
    payload.extend_from_slice(&[0xCA, 0xFE, 0xBA, 0xBE]);
    payload.push(b';');

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"KU", &payload));
    assert_not_ec68(&resp, "KU issuer script MAC");
    let (ec, _) = parse_thales_response(&resp);
    assert_eq!(&ec, b"00", "KU failed: {}", String::from_utf8_lossy(&ec));
}

/// KY: same wire format as JU/KU, EMV 4.x variant.
#[test]
#[ignore = "requires live proxy with LTEST_M3_MAC_001 in proxy.yaml"]
fn thales_ky_issuer_script_mac_generates() {
    let mut payload = Vec::new();
    payload.push(b'0');
    payload.push(b'0');
    payload.extend_from_slice(b"000");
    payload.extend_from_slice(b"LTEST_M3_MAC_001");
    payload.extend_from_slice(&[0x41, 0x11, 0x11, 0x11, 0x11, 0x11, 0x01, 0xFF]);
    payload.extend_from_slice(&[0x00, 0x03]); // ATC = 3 (different from JU/KU)
    payload.extend_from_slice(b"0004");
    payload.extend_from_slice(&[0x11, 0x22, 0x33, 0x44]);
    payload.push(b';');

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"KY", &payload));
    assert_not_ec68(&resp, "KY issuer script MAC");
    let (ec, _) = parse_thales_response(&resp);
    assert_eq!(&ec, b"00", "KY failed: {}", String::from_utf8_lossy(&ec));
}

// ── EA/EC ZPK-mode PIN verify (same handler as DA/DC, different key type label) ─

/// EA IBM 3624 verify via ZPK: identical to DA but command code is EA.
/// Reuses same test vector as DA (Level 2 confirmed).
#[test]
#[ignore = "requires live proxy with known-material V1 and P0SRC keys in proxy.yaml"]
fn thales_ea_ibm3624_verify_correct_pin() {
    let mut payload = Vec::new();
    payload.extend_from_slice(b"LTEST_P0SRC_0001");
    payload.extend_from_slice(b"LTEST_V1PVK_0001");
    payload.extend_from_slice(b"12");
    payload.extend_from_slice(b"04");
    payload.extend_from_slice(b"C30C31411AA3D043");
    payload.extend_from_slice(b"00");
    payload.extend_from_slice(b"111111111111");
    payload.extend_from_slice(b"0123456789012345");
    payload.extend_from_slice(b"111111111111");
    payload.extend_from_slice(b"9237FFFFFFFF");

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"EA", &payload));
    assert_ec00(&resp, "EA IBM 3624 PIN verify (correct PIN)");
}

/// EC Visa PVV verify via ZPK: identical to DC but command code is EC.
/// Reuses same test vector as DC (Level 2 confirmed, PVV=3361).
#[test]
#[ignore = "requires live proxy with known-material V2 and P0SRC keys in proxy.yaml"]
fn thales_ec_visa_pvv_verify_correct_pin() {
    let mut payload = Vec::new();
    payload.extend_from_slice(b"LTEST_P0SRC_0001");
    payload.extend_from_slice(b"LTEST_V2PVK_0001LTEST_V2PVK_0001");
    payload.extend_from_slice(b"12");
    payload.extend_from_slice(b"04");
    payload.extend_from_slice(b"C30C31411AA3D043");
    payload.extend_from_slice(b"00");
    payload.extend_from_slice(b"111111111111");
    payload.push(b'1');
    payload.extend_from_slice(b"3361");

    let resp = send_recv(&make_thales_frame([0x00, 0x00], b"EC", &payload));
    assert_ec00(&resp, "EC Visa PVV verify (correct PIN)");
}
